model:
  num_msg: 25
  num_heads_core: 3
  num_heads_routing: 3
  dept_core: 1
  dept_routing: 1
  edge_encoder_kwargs:
    hidden_sizes: [64, 32, 24, 32]
    dropout_rate: 0.32
    alpha: 0.2
  node_encoder_kwargs:
    hidden_sizes: [24, 24, 32]
    dropout_rate: 0.32
    alpha: 0.2
  edge_gtt_kwargs:
    key_hidden_sizes: [32, 32, 24]
    query_hidden_sizes: [32, 32, 24]
    value_hidden_sizes: [32, 32, 24]
    predecessor_dim:
    key_dropout_rate: 0.32
    key_alpha: 0.2
    query_dropout_rate: 0.32
    query_alpha: 0.2
    value_dropout_rate: 0.32
    value_alpha: 0.2
  node_gtt_kwargs:
    value_hidden_sizes: [32, 32, 34]
    value_dropout_rate: 0.32
    value_alpha: 0.2
  edge_gr_kwargs:
    key_hidden_sizes: [32, 32, 24]
    query_hidden_sizes: [32, 32, 24]
    value_hidden_sizes: [32, 32, 24]
    key_dropout_rate: 0.32
    key_alpha: 0.2
    query_dropout_rate: 0.32
    query_alpha: 0.2
    value_dropout_rate: 0.32
    value_alpha: 0.2
  embed_core_multi_head_kwargs:
    edge_dim: 32
    node_dim: 32
  embed_routing_multi_head_kwargs:
    hidden_sizes: [32, 32]
    dropout_rate: 0.32
    alpha: 0.2
  layer_norm_gtt_kwargs:
    axis: -1
    scale: True
    offset: True
train:
  num_epochs: 60
  optimizer: "Adam"
  init_lr: 1e-3
  end_lr: 1e-5
  decay_steps: 100000
  power: 0.8
  cycle: True
  tr_size: 1000000
  tr_batch_size: 64
  val_batch_size: 64
  tr_path_data: "dataset/train/All"
  val_path_data: "dataset/validation/All"
  file_ext: "gpickle"
  seed: 12345
  msg_ratio: 0.45
  input_fields: null
  class_weights: [0.4, 1.2]
  scaler: True
  delta_time_validation: 60
  log_path: "logs"
  restore_path: null
  compile: True
  debug: False
