hydra:
  run:
    dir: "." 
  output_subdir: null
mlflow:
  exp_name: "training RGT"
  exp_tags: null
  run_tags: null
  run_id: null
  get_last_run: false
model:
  num_msg: 25
  num_heads_core: 4
  num_heads_routing: 4
  dept_core: 3
  dept_routing: 3
  edge_encoder_kwargs:
    conv_output_channels: [16, 64]
    conv_kernel: [4, 8]
    conv_stride: [1, 8]
    conv_padding: ['SAME', 'VALID']
    pool_ksize: [null, 4]
    pool_stride: [null, 4]
    pool_padding: [null, 'SAME']
    conv_dropout_rate: 0.25
    mlp_hidden_sizes: [32, 24, 24]
    mlp_dropout_rate: 0.32
    mlp_alpha: 0.2
    scale: True
    offset: True
  node_encoder_kwargs:
    hidden_sizes: [32, 24, 24]
    dropout_rate: 0.32
    alpha: 0.2
  edge_gtt_kwargs:
    key_hidden_sizes: [24]
    query_hidden_sizes: [24]
    value_hidden_sizes: [24]
    predecessor_dim: 24
    key_dropout_rate: 0.32
    key_alpha: 0.2
    query_dropout_rate: 0.32
    query_alpha: 0.2
    value_dropout_rate: 0.32
    value_alpha: 0.2
  node_gtt_kwargs:
    value_hidden_sizes: [24]
    value_dropout_rate: 0.32
    value_alpha: 0.2
  edge_gr_kwargs:
    key_hidden_sizes: [24]
    value_hidden_sizes: [24]
    query_conv_output_channels: [32, 32, 24]
    query_conv_kernel: [4, 8, 8]
    query_conv_stride: [1, 1, 8]
    query_conv_padding: ['SAME', 'SAME', 'VALID']
    query_pool_ksize: [null, 4]
    query_pool_stride: [null, 4]
    query_pool_padding: [null, 'VALID']
    key_dropout_rate: 0.32
    key_alpha: 0.2
    value_dropout_rate: 0.32
    value_alpha: 0.2
    query_conv_dropout_rate: 0.25
    query_scale: True
    query_offset: True
  embed_core_multi_head_kwargs:
    edge_dim: 24
    node_dim: 24
  embed_routing_multi_head_kwargs:
    hidden_sizes: [24, 16, 8, 1]
    dropout_rate: 0.32
    alpha: 0.2
  layer_norm_gtt_kwargs:
    axis: -1
    scale: True
    offset: True
estimator:
  num_epochs: 60
  optimizer: "RMSProp"
  init_lr: 1e-3
  end_lr: 1e-5
  decay_steps: 100000
  power: 0.8
  cycle: True
  tr_size: 1000000
  tr_batch_size: 32
  val_batch_size: 32
  tr_path_data: "/local1/caio/datasets/train/All"
  val_path_data: "/local1/caio/datasets/validation/All"
  file_ext: "gpickle"
  seed: 12345
  msg_ratio: 0.45
  node_fields: ["pos", "in_degree", "out_degree"]
  edge_fields: null
  class_weights: [0.4, 1.2]
  scaler: True
  delta_time_validation: 60
  compile: True
